# Generated by Django 6.0.6 on 2026-06-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeys',
            name='encrypted_rsa_private_key_recovery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='recovery_salt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='security_answer_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
