# Generated by Django 6.0.7 on 2026-07-09 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models

def migrate_existing_documents(apps, schema_editor):
    Document = apps.get_model('core', 'Document')
    DocumentVersion = apps.get_model('core', 'DocumentVersion')
    DocumentAccessKey = apps.get_model('core', 'DocumentAccessKey')

    for doc in Document.objects.all():
        ver = DocumentVersion.objects.create(
            document=doc,
            version_number=1,
            file_path=doc.file_path,
            iv=doc.iv
        )
        # Link access keys to this version
        for key in DocumentAccessKey.objects.filter(document_id=doc.id):
            key.version = ver
            key.save()

def rollback_existing_documents(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userkeys_otp_enabled_userkeys_otp_secret_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file_path', models.FileField(upload_to='encrypted_docs/')),
                ('iv', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.document')),
            ],
        ),
        migrations.AddField(
            model_name='documentaccesskey',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to='core.documentversion'),
        ),
        migrations.RunPython(migrate_existing_documents, rollback_existing_documents),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='document',
            name='iv',
        ),
        migrations.RemoveField(
            model_name='documentaccesskey',
            name='document',
        ),
    ]
