# Generated by Django 6.0.6 on 2026-07-14 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userkeys_encrypted_rsa_private_key_recovery_and_more'),
        ('core', '0005_alter_documentaccesskey_key_type_group_and_more'),
    ]

    operations = [
    ]
