# Generated by Django 6.0.7 on 2026-07-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260713_2223'),
        ('core', '0006_merge_20260714_0518'),
    ]

    operations = [
    ]
